apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: techcrush-html-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techcrush-html-deployment

  minReplicas: 2
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # Scale up if avg CPU exceeds 70%