apiVersion: v1
kind: Service

metadata:
  name: techcrush-html-service
  labels:
    app: techcrush-html

spec:
  type: NodePort # Expose service on the node's IP

  selector:
    app: techcrush-html

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Must be between 30000-32767